--CREATE DATABASE PROJECT_TEMPLATE

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRTE_USERS]') AND type in (N'U'))
   DROP TABLE PRTE_USERS
go


CREATE TABLE PRTE_USERS
(
	USER_id INT NOT NULL,
	USER_username VARCHAR(20) NOT NULL,
	USER_password VARCHAR(MAX) NOT NULL,
	USER_firstName VARCHAR(25),
	USER_lastName VARCHAR(25),
	USER_name VARCHAR(50),
	USER_photoUrl VARCHAR(200)
);

